version: '3'
services:
  udagram-users:
    build:
      context: ../../udagram-api-users
      dockerfile: Dockerfile
    image: nickyasaph/udagram-api-users
  udagram-feed:
    build:
      context: ../../udagram-api-feed
      dockerfile: Dockerfile
    image: nickyasaph/udagram-api-feed
  reverseproxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: nickyasaph/reverseproxy
  udagram-frontend:
    build:
      context: ../../udagram-frontend
    image: nickyasaph/udagram-frontend
