apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed
  labels:
    service: udagram-api-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udagram-api-feed
  template:
    metadata:
      labels:
        service: udagram-api-feed
    spec:
      containers:
        - name: udagram-api-feed
          image: nickyasaph/udagram-api-feed:latest
          resources:
            requests:
              memory: '64Mi'
              cpu: '250m'
            limits:
              memory: '1024Mi'
              cpu: '500m'
          env:
            - name: http://localhost:8100
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: http://localhost:8100
            - name: udagram-nick
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: udagram-nick
            - name: eb-cli
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: eb-cli
            - name: us-east-1
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: us-east-1
            - name: hello
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: hello
            - name: nicki
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: nicki
            - name: nicki.cr9cvmnikkno.us-east-1.rds.amazonaws.com
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: nicki.cr9cvmnikkno.us-east-1.rds.amazonaws.com
            - name: josephtob
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: josephtob
            - name: nicki
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: nicki
      restartPolicy: Always
